---
title: "Teaching and Learning Materials"
output:
    html_document:
        toc: false
---

Right now, this page serves as the home for my materials for the CSHL Statistical Methods for Functional Genomics.

The materials are located in the "R and Bioconductor" tab at the top right, mainly. Links to slides are under the "slides"
tab above. Finally, there are some additional and miscellaneous materials in the "Misc." tab.

Materials here are licensed as [CC BY-NC-SA 4.0 Creative Commons License.](https://creativecommons.org/licenses/by-nc-sa/4.0/)

*To get the materials downloaded to your computer, [click here](https://github.com/seandavi/ITR/archive/master.zip).* 

## R
- [Getting started: R Mechanics](r_intro_mechanics.html) [[Rmd](r_intro_mechanics.Rmd)]
- [Vectors](vectors.html) [[Rmd](vectors.Rmd)] [[Exercises](vector_exercises.html)]
- [Matrices](matrices.html) [[Rmd](matrices.Rmd)]
- [Dataframes](dataframes_intro.html) [[Rmd](dataframes_intro.Rmd)]
- [Introduction to dplyr](dplyr_intro_msleep.html) [[Rmd](dplyr_intro_msleep.Rmd)] [[Exercises](dplyr_dataframes.html)]
- [Control structures, looping, and functions](control_looping_functions.html) [[Rmd](control_looping_functions.Rmd)]
- [Intro to univariate statistics](eda_and_univariate_brfss.html) [[Rmd](control_looping_functions.Rmd)]
- [Introduction to plotting](B5_plotting.html) [[Rmd](B5_plotting.Rmd)]
- [Data input and manipulation exercises](data_input_and_manipulation_exercises.html)
- [Swirl](swirl.html)
- [t-statistic](t-stats-and-tests.html) [[Rmd](t-stats-and-tests.Rmd)]
- [Machine Learning](machine_learning_mlr3.html)[[Rmd](machine_learning_mlr3.Rmd)]

## Bioconductor

- [Getting Started with Bioconductor](bioc_installation.html) [[Rmd](bioc_installation.Rmd)]
- [SummarizedExperiment](Bioc_SummarizedExperiment.html) [[Rmd](Bioc_SummarizedExperiment.Rmd)] [[Exercises](bioc_summarizedExperiment_exercises.html)]
- [AnnotationHub](AnnotationHub.html) [[Rmd](AnnotationHub.Rmd)] [[Exercises](AnnotationHubExercises.html)]
- [GEOquery and Multidimensional Scaling Exercise](geoquery_mds.html) [[Rmd](geoquery_mds.Rmd)]
- [Ranges](RangesAndSignal.html) [[Rmd](RangesAndSignal.Rmd)] [Ranges Exercises](ranges_exercises.html) [[Rmd](ranges_exercises.Rmd)] [[slides](https://bioconductor.org/packages/release/bioc/vignettes/GenomicRanges/inst/doc/GRanges_and_GRangesList_slides.pdf)] 
- [TxDb](transcriptdb.html) [[Rmd](transcriptdb.Rmd)]
- [Kmeans example](kmeans_example.html) [[Rmd](kmeans_example.Rmd)]
- [Dimensionality Reduction](dimension-reduction.html) [[Rmd](dimension-reduction.Rmd)]
- [Gene Expression Prediction](expression-prediction.html) [[Rmd](expression-prediction.Rmd)] [[Slides](expression-prediction/Expression_prediction_slides.pptx)]
- [Gene Expression and DNAse setup](ExpressionData.html) [[Rmd](ExpressionData.Rmd)]

